Feature/create football app UI/cal 2182
Gio481/FootballApp pull request #1
Opened 2022-05-10 11:01 UTC by Gio481

https://spaceneobank.atlassian.net/browse/CAL-2182

2022-05-10 11:27 UTC, AnaRusadze requested changes

2022-05-10 11:27 UTC, AnaRusadze commented on app/src/main/java/com/example/footballapp/presentation/custom_view/ClubsBallPossessionCustomView.kt
> +    }
custom viewს ჯობია, რომ ბაინდინგი ლეიზით არ გამოუცხადო

2022-05-10 11:27 UTC, AnaRusadze commented on app/src/main/java/com/example/footballapp/presentation/custom_view/ClubsInfoCustomView.kt
> +    }
არც აქ

2022-05-10 11:27 UTC, AnaRusadze commented on app/src/main/java/com/example/footballapp/presentation/custom_view/MatchInfoCustomView.kt
> +    }
არც აქ

2022-05-10 11:27 UTC, AnaRusadze commented on app/src/main/java/com/example/footballapp/util/extensions/StringExtension.kt
> +        if (it in 48.toChar()..56.toChar()) {
48 56 რისი აღმნიშვნელია?

2022-05-10 11:56 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/util/extensions/StringExtension.kt
> +        if (it in 48.toChar()..56.toChar()) {
რისი და ASCII ში 0-9 მდე ციფრების ჩარებია ამ შუალედში

2022-05-10 11:57 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/presentation/custom_view/ClubsBallPossessionCustomView.kt
> +    }
done

2022-05-10 11:57 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/presentation/custom_view/ClubsInfoCustomView.kt
> +    }
done

2022-05-10 11:57 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/presentation/custom_view/MatchInfoCustomView.kt
> +    }
done

2022-05-17 11:13 UTC, gioqemoklidze commented on app/src/main/java/com/example/footballapp/util/extensions/StringExtension.kt
> +        if (it in 48.toChar()..56.toChar()) {
ამაზე ხო ვილაპარაკეთ და პირდაპირ ხოუნდა დაგესეტა ? @Gio481

2022-05-17 11:46 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/util/extensions/StringExtension.kt
> +        if (it in 48.toChar()..56.toChar()) {
კი ამოღებული მაქვს

2022-05-17 11:51 UTC, shioandghuladze approved these changes

2022-05-18 11:41 UTC, gioqemoklidze approved these changes

2022-05-18 11:49 UTC, AnaRusadze commented on app/src/main/java/com/example/footballapp/MainActivity.kt
> +            supportFragmentManager.findFragmentById(R.id.mainNavHostFragment) as NavHostFragment
find view by id bindingis dros agar dagchirdeba

2022-05-18 11:57 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/MainActivity.kt
> +            supportFragmentManager.findFragmentById(R.id.mainNavHostFragment) as NavHostFragment
ისე იქრაშებოდა და მაგიტო მომიწია ასე

2022-05-18 13:04 UTC, AnaRusadze requested changes

2022-05-18 13:18 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/MainActivity.kt
> +            supportFragmentManager.findFragmentById(R.id.mainNavHostFragment) as NavHostFragment
რამდენიმე ფარგმენტი რო მქონდეს მაგ შემთხვევაში ?

2022-05-18 13:25 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/presentation/base/BaseFragment.kt
> +        viewModel = getViewModel(clazz = getViewModelClass())
viewModel ისთვის factory კლასის შექმნა მომიწევს მაშინ vm - ს კონსტრუქტორში გადაწოდებული პარამეტრებისთვის ან კონსტრუქტორში არ გადავაწოდო და ცვლადებად მქონდეს

2022-05-18 13:59 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/presentation/base/BaseFragment.kt
> +        viewModel = getViewModel(clazz = getViewModelClass())
done

2022-05-19 07:28 UTC, AnaRusadze requested changes

2022-05-19 07:28 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
ეს ტექსტიც წაშალე და კიდევ გიტიგნორში დაამატე idea ფაილები და ეგაა

2022-05-19 21:26 UTC, Gio481 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
done

2022-05-20 09:18 UTC, AnaRusadze commented on .gitignore
> +/.idea/deploymentTargetDropDown.xml
.idea/** პირდაპირ ესეც შეგიძლია დაამატო, რომ ყველაფერი მოიცვას

2022-05-20 09:19 UTC, merged