[CAL-2220] Feature/display data to the UI/cal 2220
Gio481/FootballApp pull request #6
Opened 2022-05-27 08:45 UTC by Gio481

https://spaceneobank.atlassian.net/plugins/servlet/mobile?originPath=%2Fbrowse%2FCAL-2220#issue/CAL-2220

2022-05-27 08:46 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/footballapp/domain/usecase/GetFootballMatchUseCaseImpl.kt
> +        }
when()

2022-05-27 08:46 UTC, GiorgiMamagulashvil1 approved these changes

2022-05-27 08:47 UTC, AleksandreGalogreBaramidze approved these changes

2022-05-27 09:05 UTC, shioandghuladze requested changes

2022-05-27 09:05 UTC, shioandghuladze commented on app/src/main/java/com/example/footballapp/domain/usecase/GetFootballMatchUseCaseImpl.kt
> +    override suspend fun getSecondHalfScore(action: (message: String) -> Unit): String {
ამ ფუნქციასა და getFirstHalfScore ფუნქციას შორის მხოლოდ ისაა განსხვავებული რომ 0..45 ის მაგივრად 46..90 გადაეწოდება countGoals ფუნქციას, ასე როცა ხდება ხოლმე ესეიგი გასაერთიანებელია ორი ფუნქცია რამე ერთში

2022-05-28 09:43 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/domain/usecase/GetFootballMatchUseCaseImpl.kt
> +        }
done

2022-05-28 09:51 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/domain/usecase/GetFootballMatchUseCaseImpl.kt
> +    private fun makeTeamsScoresNull() {
done

2022-05-28 09:51 UTC, Gio481 commented on app/src/main/java/com/example/footballapp/domain/usecase/GetFootballMatchUseCaseImpl.kt
> +    override suspend fun getSecondHalfScore(action: (message: String) -> Unit): String {
done

2022-05-30 12:42 UTC, AnaRusadze approved these changes

2022-05-30 12:42 UTC, merged